version: '3.8'

services:
  app:
    image: nodeapi
    environment:
      - MONGO_URL=mongodb://db:27017/test
    depends_on:
      - db
    ports:
      - '3000:5000'

  db:
    image: mongo
